[workspace]
resolver = "2"
members = [
    "ContractsRevo/ExampleContract",
    "ContractsRevo/PurchaseReviewContract",
    "ContractsRevo/RatingSystemContract",
    "ContractsRevo/TransactionNFTContract",
]


[workspace.dependencies]
soroban-sdk = "22.0.0-rc.3.2"