[workspace]
members = [
    "ContrctsRevo/ExampleContract",
    "ContrctsRevo/PurchaseReviewContract",
    "ContrctsRevo/RatingSystemContract",
    "ContrctsRevo/TransactionNFTContract",
]

[workspace.dependencies]
soroban-sdk = "22.0.0-rc.3.2"