[workspace]
members = [
    "ContractsRevo/ExampleContract",
    "ContractsRevo/PurchaseReviewContract",
    "ContractsRevo/rating-system-contract",
    "ContractsRevo/TransactionNFTContract",
]

[workspace.dependencies]
soroban-sdk = "22.0.0-rc.3.2"