[package]
name = "equipment-rental-contract"
version = "0.1.0"
edition = "2021"

[dependencies]
soroban-sdk = "22.0.6"

[dev-dependencies]
soroban-sdk = { version = "22.0.6", features = ["testutils"] }

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"
